### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by bursteinalan** [CS521-Burstein/final-project-MartinBourbier-JennyHopkins-AigerimDussikenova#8]
- You don't have to use branches (I'm happy your are) but I don't understand why there are 4
- Don't really know what's going on with the html file (if it has useful new info let me know and I'll download and load it)
- exploring_data.ipynb needs more visual components, you can have a lot of interesting plots with a couple of variables and then color based on accepting or deny: income vs accept or deny, income vs age with accept or deny coloring.
- Lot of potential here!

**Comment by MartinBourbier** [comment]
The HTML file contains all the information about the data we have extracted. So I think it could be interesting for you tu check it out. Thanks for the review!
